spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vocacional_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:rumbo_app_dev}

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=${DB_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false

spring.sql.init.mode=${DB_SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=true
